queue:
  driver: amqp
  config:
    connectRetries: 20
    # applies to all consumers for now
    prefetchCount: 5
    url: amqp://rabbit:rabbit@rabbitmq
    topology:
      exchanges:
        - name: example-arnavon
          default: true
          type: topic
          options:
            durable: true
        - name: dead-letters
          type: topic
          options:
            durable: true
        - name: invalid-jobs
          type: topic
          options:
            durable: true
      queues:
        - name: send-email
          options:
            durable: true
            deadLetterExchange: dead-letters
          bindings:
            - routingKey: send-email
              exchange: example-arnavon
        - name: send-email-via-binary
          options:
            durable: false
          bindings:
            - routingKey: send-email-via-binary
              exchange: example-arnavon
        - name: dead-letters
          options:
            durable: true
          bindings:
            - routingKey: '#'
              exchange: dead-letters
        - name: invalid-jobs
          options:
            durable: true
          bindings:
            - routingKey: '#'
              exchange: invalid-jobs

jobs:
  - name: send-email
    inputSchema: Email.Full
    invalidJobExchange: invalid-jobs
  - name: send-email-via-binary
    inputSchema: Email.Full
    invalidJobExchange: invalid-jobs
  - name: log-info
    inputSchema: .

consumers:
  - name: mailer-worker
    queue: send-email
    runner:
      type: nodejs
      config:
        module: ./consumers/mailer-worker
  - name: mailer-worker-ruby
    queue: send-email-via-binary
    runner:
      type: binary
      config:
        path: ./consumers/mailer-worker.rb
  - name: log-failures
    queue: dead-letters
    runner:
      type: nodejs
      config:
        module: ./consumers/logger
