queue:
  driver: amqp
  config:
    url: amqp://rabbit:rabbit@localhost
    topology:
      exchanges:
        - name: arnavon
          type: topic
          options:
            durable: true
      queues:
        - name: send-email
          options:
            durable: true
          bindings:
            - exchange: arnavon
              routingKey: send-email
        - name: send-slack
          options:
            durable: true
          bindings:
            - exchange: arnavon
              routingKey: send-slack
        - name: logger
          options:
            durable: true
          bindings:
            - exchange: arnavon
              routingKey: '#'

jobs:
  - name: send-slack
    inputSchema: SlackMessage

  - name: send-email
    inputSchema: Email.Full

consumers:
  - name: slack-worker
    jobSelector: send-slack
    runner:
      type: nodejs
      config:
        module: ./slack-worker

  - name: mailer-worker
    jobSelector: send-email
    runner:
      type: nodejs
      config:
        module: ./mailer-worker

  - name: logger
    jobSelector: '*'
    runner:
      type: nodejs
      config:
        module: ./logger
