queue:
  driver: amqp
  config:
    url: amqp://rabbit:rabbit@rabbitmq
    topology:
      exchanges:
        - name: example-arnavon
          default: true
          type: topic
          options:
            durable: true
      queues:
        - name: send-email
          options:
            durable: true
          bindings:
            - routingKey: send-email
              exchange: example-arnavon

jobs:
  - name: send-email
    inputSchema: Email.Full

consumers:
  - name: mailer-worker
    queue: send-email
    runner:
      type: nodejs
      config:
        module: ./consumers/mailer-worker
