queue:
  driver: amqp
  config:
    connectRetries: 20
    url: amqp://rabbit:rabbit@rabbitmq
    topology:
      exchanges:
        - name: example-arnavon
          default: true
          type: topic
          options:
            durable: true
      queues:
        - name: send-email
          options:
            durable: true
          bindings:
            - routingKey: send-email
              exchange: example-arnavon
        - name: log-info
          options:
            durable: false
          bindings:
            - routingKey: log-info
              exchange: example-arnavon

jobs:
  - name: send-email
    inputSchema: Email.Full
  - name: log-info
    inputSchema: .

consumers:
  - name: mailer-worker
    queue: send-email
    runner:
      type: nodejs
      config:
        module: ./consumers/mailer-worker
  - name: logger
    queue: log-info
    runner:
      type: nodejs
      config:
        module: ./consumers/logger
