queue:
  driver: amqp
  config:
    url: amqp://rabbit:rabbit@localhost?heartbeat=10
    topology:
      # One exchange must be tagged as the default
      exchanges:
        - name: test-arnavon
          default: true
          type: topic
          options:
            durable: true
        - name: dead-letters
          type: topic
          options:
            durable: true
      queues:
        - name: send-email
          options:
            durable: true
          bindings:
            - routingKey: send-email
              exchange: test-arnavon
        - name: send-slack
          options:
            durable: true
          bindings:
            - routingKey: send-slack
              exchange: test-arnavon
        - name: logger
          options:
            durable: true
          bindings:
            - routingKey: '#'
              exchange: test-arnavon

jobs:
  - name: send-slack
    inputSchema: SlackMessage

  - name: send-email
    inputSchema: Email.Full

consumers:
  - name: slack-worker
    queue: send-slack
    runner:
      type: nodejs
      config:
        module: ./slack-worker

  - name: mailer-worker
    queue: send-email
    runner:
      type: nodejs
      config:
        module: ./mailer-worker

  - name: logger
    queue: logger
    runner:
      type: nodejs
      config:
        module: ./logger
