queue:
  driver: amqp
  config:
    url: amqp://rabbit:rabbit@localhost

jobs:
  - id: send-slack
    inputSchema: SlackMessage

  - id: send-email
    inputSchema: Email.Full

consumers:
  - id: slack-worker
    jobSelector: send-slack
    runner:
      type: nodejs
      config:
        module: ./slack-worker

  - id: mailer-worker
    jobSelector: send-email
    runner:
      type: nodejs
      config:
        module: ./mailer-worker

  - id: logger
    jobSelector: '*'
    runner:
      type: nodejs
      config:
        module: ./logger
