queue:
  driver: amqp
  config:
    url: amqp://rabbit:rabbit@localhost
    topology:
      # For now it is mandatory to use an exchange.
      # The exchange type can be customized though
      # & its options as well
      exchange:
        name: test-arnavon
        type: topic
        options:
          durable: true
      queues:
        - name: send-email
          options:
            durable: true
          bindings:
            - routingKey: send-email
        - name: send-slack
          options:
            durable: true
          bindings:
            - routingKey: send-slack
        - name: logger
          options:
            durable: true
          bindings:
            - routingKey: '#'

jobs:
  - name: send-slack
    inputSchema: SlackMessage

  - name: send-email
    inputSchema: Email.Full

consumers:
  - name: slack-worker
    queue: send-slack
    runner:
      type: nodejs
      config:
        module: ./slack-worker

  - name: mailer-worker
    queue: send-email
    runner:
      type: nodejs
      config:
        module: ./mailer-worker

  - name: logger
    queue: logger
    runner:
      type: nodejs
      config:
        module: ./logger
