language: node_js
node_js:
  - 14.16
cache: npm
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.28.5
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: Tests
      name: Unit Tests
      script: make test.unit

    # - stage: tests
    #   name: Integration Tests
    #   script: make test.integration

    - stage: image
      name: Building and pushing container image
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      deploy:
        provider: script
        script: make push.latest
        on:
          branch: travis

    - stage: image
      name: Building and pushing container image
      if: tags = true
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      deploy:
        provider: script
        script: make push.tag
        on:
          tags: true

    - stage: Releases
      name: Create and release packages
      script: make package
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file:
          - pkg/arnavon-linux
          - pkg/arnavon-macos
          - pkg/arnavon-win.exe
        skip_cleanup: true
        on:
          tags: true
