version: '3.3'

services:

  jobs-server:
    depends_on:
      - rabbitmq
    build: .
    ports:
      - 3000:3000
    command: ["supervisor", "--", "-r", "@babel/register", "bin/server.js"]
    volumes:
      - ./bin:/home/app/bin
      - ./src:/home/app/src
      - ./tests:/home/app/tests
      - ./package.json:/home/app/package.json
      - ./babel.config.json:/home/app/babel.config.json
      - ./.eslintrc.js:/home/app/.eslintrc.js
    env_file: ./env/devel.env

  jobs-consumer:
    depends_on:
      - rabbitmq
    build: .
    command: ["supervisor", "--", "-r", "@babel/register", "bin/consumer.js", "send-casting-invitation"]
    volumes:
      - ./bin:/home/app/bin
      - ./src:/home/app/src
      - ./tests:/home/app/tests
      - ./package.json:/home/app/package.json
      - ./babel.config.json:/home/app/babel.config.json
      - ./.eslintrc.js:/home/app/.eslintrc.js
    env_file: ./env/devel.env

  rabbitmq:
    image: rabbitmq:3.8.11-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit

  webspicy:
    image: enspirit/webspicy
    entrypoint: tail
    command: ["-f", "/dev/null"]
    volumes:
      - ./webspicy:/home/app
