name: Integration.

on:
  pull_request:
    branches:
      - "master"
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Linting
        id: linting
        run: make lint

      - name: Unit Tests
        id: unit-tests
        run: make test.unit

      - name: Integration Tests
        id: integration-tests
        run: make test.integration

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()
