name: Release images.

on:
  push:
    branches:
      - "master"
    tags:
      - '*'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  tests:
    uses: Quadrabee/arnavon/.github/workflows/integration.yml@master

  release-image:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - uses: actions/checkout@v2

      - name: Get tag if exist
        run: echo "DOCKER_TAG=$(git describe --contains || echo latest)" >> $GITHUB_ENV

      - name: Build image
        run: make image
        id: build-image

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to registry
        id: push-image
        run: make image.push

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()
